// DEVELOPER NOTE:
// KEEP THIS FILE JUST FOR COMMECTS AND NOTES!
// IN PROJECT WE HAVE A 'public' FOLDER, WITH 'fonts' FOLDER INSIDE, AND 'allicon.png' INSIDE.
// DO NOT USE REMOTE FONTS.
// THIS IS A CROSS PLATFORM SOFTWARE.
//